"
A FamixCSStackTest is a test class for testing the behavior of FamixCSStack
"
Class {
	#name : 'FamixCSStackTest',
	#superclass : 'TestCase',
	#category : 'Famix-CallStack-Entities-Tests-Entities',
	#package : 'Famix-CallStack-Entities-Tests',
	#tag : 'Entities'
}

{ #category : 'tests' }
FamixCSStackTest >> testIndexOfLine [
	"to test:
	- adding one make it at an superior index than the last one added"
	self fail
]

{ #category : 'tests' }
FamixCSStackTest >> testNextTo [
	"to test:
	- add two line and test if the second is next to the first"
	self fail
]

{ #category : 'tests' }
FamixCSStackTest >> testPreviousTo [
	"to test:
	- add two line and test if the first is previous to the second"
	self fail
]
