"
A FamixCSStringReferenceTest is a test class for testing the behavior of FamixCSStringReference
"
Class {
	#name : 'FamixCSStringReferenceTest',
	#superclass : 'TestCase',
	#category : 'Famix-CallStack-Entities-Tests-Entities',
	#package : 'Famix-CallStack-Entities-Tests',
	#tag : 'Entities'
}

{ #category : 'tests' }
FamixCSStringReferenceTest >> testFillFrom [
	"To test:
	- Does add the String as a value"
	self fail.
]
