"
A FamixCSArrayReferenceTest is a test class for testing the behavior of FamixCSArrayReference
"
Class {
	#name : 'FamixCSArrayReferenceTest',
	#superclass : 'TestCase',
	#category : 'Famix-CallStack-Entities-Tests-Entities',
	#package : 'Famix-CallStack-Entities-Tests',
	#tag : 'Entities'
}

{ #category : 'importing' }
FamixCSArrayReferenceTest >> testsize [
	"to test:
	- adding an element augment the size, and reseting element reset the size"
	self fail
]
