"
A FamixCSClassReferenceTest is a test class for testing the behavior of FamixCSClassReference
"
Class {
	#name : 'FamixCSClassReferenceTest',
	#superclass : 'TestCase',
	#category : 'Famix-CallStack-Entities-Tests-Entities',
	#package : 'Famix-CallStack-Entities-Tests',
	#tag : 'Entities'
}

{ #category : 'tests' }
FamixCSClassReferenceTest >> testFillFrom [
	"To test:
	- When prepared and not prepared
	- Does add values ton fields"
	self fail.
]
