"
A FamixCSStacklineTest is a test class for testing the behavior of FamixCSStackline
"
Class {
	#name : 'FamixCSStacklineTest',
	#superclass : 'TestCase',
	#category : 'Famix-CallStack-Entities-Tests-Entities',
	#package : 'Famix-CallStack-Entities-Tests',
	#tag : 'Entities'
}

{ #category : 'tests' }
FamixCSStacklineTest >> testIndex [
	"to test:
	- adding one make it at an superior index than the last one added"
	self fail
]

{ #category : 'tests' }
FamixCSStacklineTest >> testNext [
	"to test:
	- add two line and test if the second is next to the first"
	self fail
]

{ #category : 'tests' }
FamixCSStacklineTest >> testPrevious [
	"to test:
	- add two line and test if the first is previous to the second"
	self fail
]
