Extension { #name : 'FamixCSEntity' }

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isArgument [

	^ false
]

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isArrayReference [

	^ false
]

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isClassReference [

	^ false
]

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isField [

	^ false
]

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isStackline [

	^ false
]

{ #category : '*Famix-CallStack-Entities-Extensions' }
FamixCSEntity >> isStringReference [

	^ false
]
